name: Actualizar README

on:
  # Ejecutar este flujo de trabajo todos los días a la medianoche UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generar imagen de estadísticas
        # Genera la imagen de estadísticas localmente utilizando la acción oficial
        uses: alexcrimiesz/github-readme-stats@v2.7.0
        with:
          # Personaliza el contenido de las estadísticas según sea necesario
          username: alex-Style1007
          show_icons: true
          locale: en
          layout: compact
          line_height: 20
          title_color: 7A7ADB
          icon_color: 2234AE
          text_color: D3D3D3
          bg_color: '0,000000,130F40'
          cache: true

      - name: Actualizar README
        run: |
          mv readme.svg README.md  # Cambia el nombre de la imagen a README.md

      - name: Agregar y confirmar cambios
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Actualizar README con las estadísticas más recientes'
          git push
