name: Update README

on:
  schedule:
    # Se ejecuta una vez al día
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          curl -o README.md https://raw.githubusercontent.com/alex-Style1007/alex-Style1007/main/README.md
          sed -i 's|<img src="https://github-readme-stats.vercel.app/api/top-langs?username=alex-Style1007&show_icons=true&locale=en&layout=compact&line_height=20&title_color=7A7ADB&icon_color=2234AE&text_color=D3D3D3&bg_color=0,000000,130F40" width="375"  alt="alex-Style1007"/>|<img src="https://github-readme-stats.vercel.app/api/top-langs?username=alex-Style1007&show_icons=true&locale=en&layout=compact&line_height=20&title_color=7A7ADB&icon_color=2234AE&text_color=D3D3D3&bg_color=0,000000,130F40" width="375"  alt="alex-Style1007"/>|' README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest stats'
          git push
